### ISSUE TITLE
Update content WRT current website

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/website#1]
Need to:
- [x] Add surveys page
- [x] Remove posts that came with themes
- [x] Migrate content from home page to about
- [x] Spruce up home page
- [x] Remove tags and categories from nav bar
- [x] Add post about first survey

**Comment by martinjrobins** [comment]
I've cleaned up the home page a bit and added some links. Anything else we need to add?

**Comment by fcooper8472** [comment]
The site notice page (link in each footer) needs updating.  Perhaps a good place to mention hugo, the theme we're using, and copyright notice for the font?

**Comment by martinjrobins** [comment]
Is the license for the fonts the roboto one?

**Comment by fcooper8472** [comment]
No, but that's on the only one I've added.  Copyright/license info for the other fonts is bundled in the theme we're using.

**Comment by martinjrobins** [comment]
great, so I've mentioned we r using roboto and what the licence is. Added ethics approval and links to hugo and the theme in the site notice

**Comment by fcooper8472** [comment]
Can this be closed now?

**Comment by martinjrobins** [comment]
what did you have in mind for the surveys page?

**Comment by fcooper8472** [comment]
Just to mirror the page from the old website, but that's pretty well covered by the post you added.

**Comment by martinjrobins** [comment]
Great, we can close it then
