### ISSUE TITLE
Table of contents and back to top button

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/website#10]
Want to set up a table of contents and "back to top" button.

Back to top is probably most relevant on mobile, but possibly useful on desktop as well.

Table of contents ought to be an optional settable parameter: suggest
```
include_toc: true
```
in individual page front matter.

**Comment by fcooper8472** [comment]
The "back to top" can initially be on every page, and will be a hyperlink element that floats in the botton-right of the viewport.

**Comment by fcooper8472** [comment]
Initial work complete.  Might need to work a little bit on how it all looks.  @martinjrobins can you deploy and see how lit looks?

**Comment by martinjrobins** [comment]
perhaps we can add a tool-tip text that says "back to top" or similar when you hover over the up-arrow?

**Comment by fcooper8472** [comment]
Done
