### ISSUE TITLE
Add google analytics to site

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/website#2]
Looks straightforward:

https://gohugo.io/templates/internal/

**Comment by martinjrobins** [comment]
added tracking code UA-48149829-6

Do you have a google account @fcooper8472?, can you see the data for this code? if not I'll try to add you to the list

**Comment by fcooper8472** [comment]
Don't think I can see data for that code.  Never used analytics before though so not sure!

My google account is fcooper8472@gmail.com

**Comment by martinjrobins** [comment]
I've added you to the account, sorry about all the other webpages on there, but I'm finding the google analytics account setup rather confusing, and its easier just keeping everything in one account

**Comment by fcooper8472** [comment]
Great - seems to be working as expected!
