### ISSUE TITLE
Improve accessibility and tidy up HTML/CSS

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/website#23]
Oxford gives some advice for hosting websites:
https://help.it.ox.ac.uk/web/personalwebpages/personalguide

This includes running a site through:
- [an HTML validator](http://validator.w3.org/)
- [a CSS validator](http://jigsaw.w3.org/css-validator/)
- [an accessibility validator](http://wave.webaim.org/)

**Comment by fcooper8472** [comment]
For instance, it is highly recommended to left-align (rather than justify) passages of text.

https://github.com/OxfordRSE/website/commit/6e4d25746040d85ac1f724d87a63a2e2c65c03a3 addresses this.

**Comment by martinjrobins** [comment]
@fcooper8472, can this be closed now?

**Comment by fcooper8472** [comment]
Yep, think we've hit everything important on this!

Good to keep in mind to regularly re-assess when we add content, just to make sure we're up to scratch.
