### ISSUE TITLE
Fix nav bar on mobile devices

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/website#3]
On mobile devices the logo leaves the nav bar and the links flow onto two lines.

**Comment by martinjrobins** [comment]
edits for #1 (remove categories and tags links) fixed this

**Comment by fcooper8472** [comment]
Reopening this as the logo still gets bigger than the nav bar on mobile.  I'll have a fiddle when I get the time.

**Comment by fcooper8472** [comment]
The logo and links are now in separate classes both with
```
display: inline-block;
```
The logo has a max width of 39%, and the links have a min width of 59% so that (with wiggle room) they always take up 100% width of their parent container.  This gets around needing to float either of them, which seems to make life much easier!

Potential problem if we were ever to add many more links, but it works well on web and mobile for now!
