### ISSUE TITLE
Temporary fix for forbidden access error for Projects link

### ISSUE THREAD

**Issue by mihaeladuta** [OxfordRSE/website#31]
The Projects header link returns a forbidden access error - while we are still not ready to release that page, we should delete the Projects entry in the header because it is not good PR to have empty/in construction pages. Particularly important for the ISSF funding application to have a clean and coherent page.

**Comment by fcooper8472** [comment]
Sounds like a permissions issue... @martinjrobins if you're in front of your laptop could you have a quick look?  I won't be able to have a look this side of 10am

**Comment by mihaeladuta** [comment]
If the page is empty or is only a "under construction" stud, can we please just remove the link from the header menu? Better not to have a page than an empty page!

**Comment by martinjrobins** [comment]
only ferper has access to the projects directory. there is no index.html file there though...

**Comment by fcooper8472** [comment]
Odd.  The deploy script adds group write permissions to all directories, so I think we should all have access to every directory?

Either way this seems to be fixed for now.
