### ISSUE TITLE
fix issues with transition to www.rse.ox.ac.uk

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/website#32]
Hi Martin,

DNS issue found and fixed. It's now live everywhere.

If we're moving from www.cs.ox.ac.uk/projects/RSE/ and rse.cs.ox.ac.uk to
www.rse.ox.ac.uk, could the HTML be updated to use the new host name and base
path?

e.g. /projects/RSE becomes / and www.cs.ox.ac.uk/projects/RSE/ becomes
www.rse.ox.ac.uk/

It's currently working because I've put in HTTP redirects for
https://www.cs.ox.ac.uk/projects/RSE/ and /projects/RSE/(.*)
https://github.com/OxfordRSE/website/search?q=projects%2FRSE%2F&unscoped_q=projects%2FRSE%2F

Thanks,

Ed

P.S. There's no major hurry for that. The forward from rse.cs.ox.ac.uk will
stop when the certificate for rse.cs.ox.ac.uk expires Oct 2021.
P.P.S. The links to David, you and Graham are broken on the people page because
they should be pointing at www.cs but the relative URL resolves to www.rse .

**Comment by fcooper8472** [comment]
These changes are now live.  @martinjrobins did you want to reply to Ed to let him know that:

- everything should now be relative to `www.rse.ox.ac.uk`
- links to people are now fixed

**Comment by martinjrobins** [comment]
thanks @fcooper8472 , I've emailed Ed now
