### ISSUE TITLE
Fix text flow on people page

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/website#4]
Currently there's some bad flow between the Martin and Fergus sections.

**Comment by martinjrobins** [comment]
added a few words to my section so that your title is on the left. How did you get the text to wrap around the images?

**Comment by fcooper8472** [comment]
In `main.css`:
```
img {
  float: left;
  padding-top: 16px;
  padding-right: 16px;
  padding-bottom: 16px;
  padding-left: 0px;
...
}
```
