### ISSUE TITLE
cpp template project

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/website#5]
I've started a repo OxfordRSE/template-cpp-project with a template c++ project using CMake, Catch2, travis-ci, and codecov. Its something I've wanted to make up for myself, but it might be worth doing an oxford-specific version (e.g. import a few libraries, boost, openmp, eigen, vtk, and make sure it works on a few departmental setups as well as arcus), and posting it to the RSE website

@fcooper8472, any thoughts?

**Comment by fcooper8472** [comment]
Sounds like a fantastic idea!
I was wondering about, perhaps, having two kinds of blog post on the website: technical blogs (that this one be part of) and "other" (not sure what we would call it) that would include all our survey stuff, analysis, etc.
Then we might have an additional "Posts" or "Blogs" page (in the menu with People and About) with separate categories for the two types of blog, and perhaps remove them from the homepage?

**Comment by martinjrobins** [comment]
done in #6
