### ISSUE TITLE
separate blog posts into "technical" and "other" (tbd)

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/website#6]
@fcooper8472 from #5: 

"I was wondering about, perhaps, having two kinds of blog post on the website: technical blogs (that this one be part of) and "other" (not sure what we would call it) that would include all our survey stuff, analysis, etc. Then we might have an additional "Posts" or "Blogs" page (in the menu with People and About) with separate categories for the two types of blog, and perhaps remove them from the homepage?"

**Comment by fcooper8472** [comment]
#### Implementation details:
We can loop through pages in different directories under `/content/` using the `{{ range }}` functionality in `/layouts/index.html`.

#### Suggestions:
- New page called "Posts", linked to on the main nav bar and from the homepage
- Rename current `post` dir to `rse_post`
- New dir `tech_post`
- Add draft "C++ template project" tech post
- "Posts" would contain a list at the top of the RSE posts (surveys, analysis, etc), with a list of tech posts underneath

How does that sound?

**Comment by fcooper8472** [comment]
Slightly trickier than anticipated, but should be done now.  @martinjrobins can you have a look and deploy if it's working for you?

**Comment by martinjrobins** [comment]
yup, these changes sounds good. I've deployed the latest, but get an error when I go to "posts"

/* Natrium doesn't support list.html. */

**Comment by fcooper8472** [comment]
Woops - draft tag on the `posts.md` file... Should be fixed now.

**Comment by martinjrobins** [comment]
Yup, that works
